### ISSUE TITLE
dumpKernFeatureFromOTF attribute error

### ISSUE THREAD

**Issue by Arno-Enslin** [adobe-type-tools/kern-dump#3]
Python 2.7.11
Windows (7)
Other scripts from kern-dump-master (07-28-2017) present.
AFDKO incl. Fonttools built on 07-06-2017.

Error message:

```
Traceback (most recent call last):
  File "dumpKernFeatureFromOTF.py", line 217, in <module>
    makeKernFeature(fontPath)
  File "dumpKernFeatureFromOTF.py", line 76, in makeKernFeature
    f = getKerningPairsFromOTF.ReadKerning(fontPath)
AttributeError: 'module' object has no attribute 'ReadKerning'
```

**Comment by frankrolf** [comment]
PRs are gladly accepted.

**Comment by Arno-Enslin** [comment]
That was very fast, Frank. Thanks! Works now.

(I don't know, what "PR" means. Hopefully nothing bad.)

**Comment by kenlunde** [comment]
PR = Pull Request

**Comment by Arno-Enslin** [comment]
> PRs are gladly accepted.

I am not sure if this was an invitation to make a pull request, because I did not modify the script, but have reported the issue only.
