### ISSUE TITLE
Create setup.py and make installable via pip

### ISSUE THREAD

**Issue by kontur** [adobe-type-tools/kern-dump#8]
It would be nice to have these scripts installable via pip, which requires a setup.py.

**Comment by frankrolf** [comment]
Since these tools are quite insular, I did never consider doing this.
If you’d like to help, I am glad to accept a PR! Thanks!

**Comment by n8willis** [comment]
I would also be interested in having this be installable via PyPI, for practical reasons. It's useful in my research, and I like to keep dependencies on that sort of stuff as clean as possible for reproducibility, etc. So it'd be super nice to have it available via pip.

Given that the set of scripts is quite small, is there a reason that it wouldn't make sense to add them to the FDK — if managing them as a standalone package is not of interest?

**Comment by frankrolf** [comment]
Hi @n8willis, I will make this a package eventually – possibly in combination with other FDK scripts (see https://github.com/adobe-type-tools/python-modules/issues/8).
The reason for those scripts not being part of the FDK is that we are trying to declutter it rather than adding more and more stuff :-)

Thanks for the nudge, please feel free to nudge me again if nothing is happening on this front.

**Comment by n8willis** [comment]
> The reason for those scripts not being part of the FDK is that we are trying to declutter it rather than adding more and more stuff :-)

Heh. Makes sense! When you put it that way.

> I will make this a package eventually – possibly in combination with other FDK scripts (see [adobe-type-tools/python-modules#8](https://github.com/adobe-type-tools/python-modules/issues/8)).

Ah; cool. That would indeed be useful as its own thing. No hurry from my POV; just glad to know it has a future.

**Comment by frankrolf** [comment]
This has been done thanks to @miguelsousa, and i also just added a setup.py to the python-modules repo.
Much more useful indeed! :-)

**Comment by kontur** [comment]
Superb, thanks 👍

**Comment by n8willis** [comment]
Thanks guys; this is great!
